import fs from 'fs';
import path from 'path';

const coreDir = path.join(__dirname, '../src/prolog');
const files = ['parser.pl', 'translator.pl', 'specializer.pl', 'filereader.pl', 'spaces.pl', 'metta.pl'];

let combinedPl = ":- op(700, xfx, '=@=').\n:- dynamic(library_path/1).\n:- dynamic(translator_rule/1).\n:- dynamic('get-type'/2).\n:- dynamic(fun/1).\n:- dynamic(silent/1).\n:- dynamic(ho_specialization/2).\n";

for (const file of files) {
    let content = fs.readFileSync(path.join(coreDir, file), 'utf8');
    content = content.replace(/:- ensure_loaded\(\[.*?\]\)\./g, '');
    content = content.replace(/:- ensure_loaded\(.*?\)\./g, '');
    content = content.replace(/:- dynamic\(.*?\)\./g, '');
    combinedPl += content + '\n';
}

const outPath = path.join(__dirname, '../src/core_pl.ts');
fs.writeFileSync(outPath, `// Auto-generated by bundle-pl.ts\nexport const CORE_PL = ${JSON.stringify(combinedPl)};\n`);
console.log(`Bundled ${files.length} prolog files into core_pl.ts`);
